export const topics = [
    {
      name: 'Tunteet — Emotions',
      wordsAndImages: [
        { en: 'happy', fi: 'onnellinen', img: 'emotions/happy.png' },
        { en: 'excited', fi: 'innostunut', img: 'emotions/excited.png' },
        { en: 'proud', fi: 'ylpeä', img: 'emotions/proud.png' },
        { en: 'in love', fi: 'rakastunut', img: 'emotions/inlove.png' },
        { en: 'grateful', fi: 'kiitollinen', img: 'emotions/grateful.png' },
        { en: 'confident', fi: 'itsevarma', img: 'emotions/confident.png' },
        { en: 'sad', fi: 'surullinen', img: 'emotions/sad.png' },
        { en: 'angry', fi: 'vihainen', img: 'emotions/angry.png' },
        { en: 'scared', fi: 'pelokas', img: 'emotions/scared.png' },
        { en: 'embarrassed', fi: 'nolostunut', img: 'emotions/embarrassed.png' },
        { en: 'frustrated', fi: 'turhautunut', img: 'emotions/frustrated.png' },
        { en: 'surprised', fi: 'yllättynyt', img: 'emotions/surprised.png' }
      ]
    },
    {
      name: 'Eläimet — Animals',
      wordsAndImages: [
        { en: 'bear', fi: 'karhu', img: 'animals/bear.png' },
        { en: 'bee', fi: 'mehiläinen', img: 'animals/bee.png' },
        { en: 'bird', fi: 'lintu', img: 'animals/bird.png' },
        { en: 'butterfly', fi: 'perhonen', img: 'animals/butterfly.png' },
        { en: 'cat', fi: 'kissa', img: 'animals/cat.png' },
        { en: 'chicken', fi: 'kana', img: 'animals/chicken.png' },
        { en: 'cow', fi: 'lehmä', img: 'animals/cow.png' },
        { en: 'dog', fi: 'koira', img: 'animals/dog.png' },
        { en: 'elephant', fi: 'norsu', img: 'animals/elephant.png' },
        { en: 'fish', fi: 'kala', img: 'animals/fish.png' },
        { en: 'fly', fi: 'kärpänen', img: 'animals/fly.png' },
        { en: 'horse', fi: 'hevonen', img: 'animals/horse.png' },
        { en: 'lion', fi: 'leijona', img: 'animals/lion.png' },
        { en: 'mosquito', fi: 'hyttynen', img: 'animals/mosquito.png' },
        { en: 'mouse', fi: 'hiiri', img: 'animals/mouse.png' },
        { en: 'pig', fi: 'sika', img: 'animals/pig.png' },
        { en: 'rabbit', fi: 'kani', img: 'animals/rabbit.png' },
        { en: 'rat', fi: 'rotta', img: 'animals/rat.png' },
        { en: 'seagull', fi: 'lokki', img: 'animals/seagull.png' },
        { en: 'sheep', fi: 'lammas', img: 'animals/sheep.png' }
      ]
    },
    
    
    {
      name: 'Ruoka — Food',
      wordsAndImages: [
        { en: 'bread', fi: 'leipä', img: 'food/bread.png' },
        { en: 'butter', fi: 'voi', img: 'food/butter.png' },
        { en: 'carrot', fi: 'porkkana', img: 'food/carrot.png' },
        { en: 'cheese', fi: 'juusto', img: 'food/cheese.png' },
        { en: 'cucumber', fi: 'kurkku', img: 'food/cucumber.png' },
        { en: 'egg', fi: 'kananmuna', img: 'food/egg.png' },
        { en: 'garlic', fi: 'valkosipuli', img: 'food/garlic.png' },
        { en: 'milk', fi: 'maito', img: 'food/milk.png' },
        { en: 'onion', fi: 'sipuli', img: 'food/onion.png' },
        { en: 'pasta', fi: 'pasta', img: 'food/pasta.png' },
        { en: 'potato', fi: 'peruna', img: 'food/potato.png' },
        { en: 'rice', fi: 'riisi', img: 'food/rice.png' },
        { en: 'salad', fi: 'salaatti', img: 'food/salad.png' },
        { en: 'soup', fi: 'keitto', img: 'food/soup.png' },
        { en: 'yoghurt', fi: 'jogurtti', img: 'food/yoghurt.png' }
      ]
    },
    
    {
      name: 'Hedelmät — Fruits',
      wordsAndImages: [
        { en: 'apple', fi: 'omena', img: 'fruits/apple.png' },
        { en: 'banana', fi: 'banaani', img: 'fruits/banana.png' },
        { en: 'blueberry', fi: 'mustikka', img: 'fruits/blueberry.png' },
        { en: 'cherry', fi: 'kirsikka', img: 'fruits/cherry.png' },
        { en: 'grapefruit', fi: 'greippi', img: 'fruits/grapefruit.png' },
        { en: 'grapes', fi: 'viinirypäleet', img: 'fruits/grapes.png' },
        { en: 'kiwi', fi: 'kiivi', img: 'fruits/kiwi.png' },
        { en: 'lemon', fi: 'sitruuna', img: 'fruits/lemon.png' },
        { en: 'lime', fi: 'limetti', img: 'fruits/lime.png' },
        { en: 'mango', fi: 'mango', img: 'fruits/mango.png' },
        { en: 'orange', fi: 'appelsiini', img: 'fruits/orange.png' },
        { en: 'peach', fi: 'persikka', img: 'fruits/peach.png' },
        { en: 'pear', fi: 'päärynä', img: 'fruits/pear.png' },
        { en: 'pineapple', fi: 'ananas', img: 'fruits/pineapple.png' },
        { en: 'plum', fi: 'luumu', img: 'fruits/plum.png' },
        { en: 'raspberry', fi: 'vadelma', img: 'fruits/raspberry.png' },
        { en: 'strawberry', fi: 'mansikka', img: 'fruits/strawberry.png' },
        { en: 'watermelon', fi: 'vesimeloni', img: 'fruits/watermelon.png' }
      ]
    },
    
    
    {
      name: 'Kulkuvälineet — Vehicles',
      wordsAndImages: [
        { en: 'airplane', fi: 'lentokone', img: 'vehicles/airplane.png' },
        { en: 'ambulance', fi: 'ambulanssi', img: 'vehicles/ambulance.png' },
        { en: 'bicycle', fi: 'polkupyörä', img: 'vehicles/bicycle.png' },
        { en: 'boat', fi: 'vene', img: 'vehicles/boat.png' },
        { en: 'bus', fi: 'bussi', img: 'vehicles/bus.png' },
        { en: 'car', fi: 'auto', img: 'vehicles/car.png' },
        { en: 'drone', fi: 'droni', img: 'vehicles/drone.png' },
        { en: 'fire truck', fi: 'paloauto', img: 'vehicles/fire_truck.png' },
        { en: 'helicopter', fi: 'helikopteri', img: 'vehicles/helicopter.png' },
        { en: 'hot air balloon', fi: 'kuumailmapallo', img: 'vehicles/hot_air_balloon.png' },
        { en: 'metro', fi: 'metro', img: 'vehicles/metro.png' },
        { en: 'motorcycle', fi: 'moottoripyörä', img: 'vehicles/motorcycle.png' },
        { en: 'police car', fi: 'poliisiauto', img: 'vehicles/police_car.png' },
        { en: 'taxi', fi: 'taksi', img: 'vehicles/taxi.png' },
        { en: 'tractor', fi: 'traktori', img: 'vehicles/tractor.png' },
        { en: 'train', fi: 'juna', img: 'vehicles/train.png' },
        { en: 'tram', fi: 'raitiovaunu', img: 'vehicles/tram.png' },
        { en: 'truck', fi: 'kuorma-auto', img: 'vehicles/truck.png' },
        { en: 'van', fi: 'pakettiauto', img: 'vehicles/van.png' }
      ]
    },
    
    {
      name: 'Koti — Home',
      wordsAndImages: [
        { en: 'bathroom', fi: 'kylpyhuone', img: 'home/bathroom.png' },
        { en: 'bed', fi: 'sänky', img: 'home/bed.png' },
        { en: 'bedroom', fi: 'makuuhuone', img: 'home/bedroom.png' },
        { en: 'blanket', fi: 'peitto', img: 'home/blanket.png' },
        { en: 'carpet', fi: 'matto', img: 'home/carpet.png' },
        { en: 'ceiling', fi: 'katto', img: 'home/ceiling.png' },
        { en: 'chair', fi: 'tuoli', img: 'home/chair.png' },
        { en: 'clock', fi: 'kello', img: 'home/clock.png' },
        { en: 'cup', fi: 'kuppi', img: 'home/cup.png' },
        { en: 'cupboard', fi: 'kaappi', img: 'home/cupboard.png' },
        { en: 'dishwasher', fi: 'astianpesukone', img: 'home/dishwasher.png' },
        { en: 'door', fi: 'ovi', img: 'home/door.png' },
        { en: 'floor', fi: 'lattia', img: 'home/floor.png' },
        { en: 'fork', fi: 'haarukka', img: 'home/fork.png' },
        { en: 'fridge', fi: 'jääkaappi', img: 'home/fridge.png' },
        { en: 'glass', fi: 'lasi', img: 'home/glass.png' },
        { en: 'home', fi: 'koti', img: 'home/home.png' },
        { en: 'house', fi: 'talo', img: 'home/house.png' },
        { en: 'kitchen', fi: 'keittiö', img: 'home/kitchen.png' },
        { en: 'knife', fi: 'veitsi', img: 'home/knife.png' },
        { en: 'lamp', fi: 'lamppu', img: 'home/lamp.png' },
        { en: 'light', fi: 'valo', img: 'home/light.png' },
        { en: 'living room', fi: 'olohuone', img: 'home/living_room.png' },
        { en: 'microwave oven', fi: 'mikroaaltouuni', img: 'home/microwave_oven.png' },
        { en: 'mirror', fi: 'peili', img: 'home/mirror.png' },
        { en: 'oven', fi: 'uuni', img: 'home/oven.png' },
        { en: 'pillow', fi: 'tyyny', img: 'home/pillow.png' },
        { en: 'plate', fi: 'lautanen', img: 'home/plate.png' },
        { en: 'room', fi: 'huone', img: 'home/room.png' },
        { en: 'shirt', fi: 'paita', img: 'home/shirt.png' },
        { en: 'sink', fi: 'allas', img: 'home/sink.png' },
        { en: 'sofa', fi: 'sohva', img: 'home/sofa.png' },
        { en: 'spoon', fi: 'lusikka', img: 'home/spoon.png' },
        { en: 'stove', fi: 'liesi', img: 'home/stove.png' },
        { en: 'table', fi: 'pöytä', img: 'home/table.png' },
        { en: 'television', fi: 'televisio', img: 'home/television.png' },
        { en: 'wall', fi: 'seinä', img: 'home/wall.png' },
        { en: 'washing machine', fi: 'pesukone', img: 'home/washing_machine.png' },
        { en: 'window', fi: 'ikkuna', img: 'home/window.png' }
      ]
    },
    
    
    {
      name: 'Yleiset verbit — Common Verbs',
      wordsAndImages: [
        { en: 'drink', fi: 'juoda', img: 'verbs1/drink.jfif' },
        { en: 'drive', fi: 'ajaa', img: 'verbs1/drive.jfif' },
        { en: 'eat', fi: 'syödä', img: 'verbs1/eat.jfif' },
        { en: 'give', fi: 'antaa', img: 'verbs1/give.jfif' },
        { en: 'hear', fi: 'kuulla', img: 'verbs1/hear.jfif' },
        { en: 'laugh', fi: 'nauraa', img: 'verbs1/laugh.jfif' },
        { en: 'lift', fi: 'nostaa', img: 'verbs1/lift.jfif' },
        { en: 'listen', fi: 'kuunnella', img: 'verbs1/listen.jfif' },
        { en: 'look', fi: 'katsoa', img: 'verbs1/look.jfif' },
        { en: 'open', fi: 'avata', img: 'verbs1/open.jfif' },
        { en: 'pull', fi: 'vetää', img: 'verbs1/pull.jfif' },
        { en: 'push', fi: 'työntää', img: 'verbs1/push.jfif' },
        { en: 'run', fi: 'juosta', img: 'verbs1/run.jfif' },
        { en: 'say', fi: 'sanoa', img: 'verbs1/say.jfif' },
        { en: 'see', fi: 'nähdä', img: 'verbs1/see.jfif' },
        { en: 'sit', fi: 'istua', img: 'verbs1/sit.jfif' },
        { en: 'sleep', fi: 'nukkua', img: 'verbs1/sleep.jfif' },
        { en: 'talk', fi: 'puhua', img: 'verbs1/talk.jfif' },
        { en: 'think', fi: 'ajatella', img: 'verbs1/think.jfif' },
        { en: 'walk', fi: 'kävellä', img: 'verbs1/walk.jfif' },
        { en: 'want', fi: 'haluta', img: 'verbs1/want.jfif' },
        { en: 'wash', fi: 'pestä', img: 'verbs1/wash.jfif' },
        { en: 'write', fi: 'kirjoittaa', img: 'verbs1/write.jfif' }
      ]
    },
    
    
    
    {
      name: 'Lisää verbejä — More Verbs',
      wordsAndImages: [
        { en: 'blow', fi: 'puhaltaa', img: 'verbs2/blow.jfif' },
        { en: 'clean', fi: 'siivota', img: 'verbs2/clean.jfif' },
        { en: 'cry', fi: 'itkeä', img: 'verbs2/cry.jfif' },
        { en: 'dig', fi: 'kaivaa', img: 'verbs2/dig.jfif' },
        { en: 'draw', fi: 'piirtää', img: 'verbs2/draw.jfif' },
        { en: 'fall', fi: 'kaatua', img: 'verbs2/fall.jfif' },
        { en: 'find', fi: 'löytää', img: 'verbs2/find.jfif' },
        { en: 'hide', fi: 'piiloutua', img: 'verbs2/hide.jfif' },
        { en: 'hug', fi: 'halata', img: 'verbs2/hug.jfif' },
        { en: 'jump', fi: 'hypätä', img: 'verbs2/jump.jfif' },
        { en: 'kiss', fi: 'suudella', img: 'verbs2/kiss.jfif' },
        { en: 'lie down', fi: 'käydä makuulle', img: 'verbs2/lie_down.jfif' },
        { en: 'paint', fi: 'maalata', img: 'verbs2/paint.jfif' },
        { en: 'pay', fi: 'maksaa', img: 'verbs2/pay.jfif' },
        { en: 'plant', fi: 'istuttaa', img: 'verbs2/plant.jfif' },
        { en: 'ski', fi: 'hiihtää', img: 'verbs2/ski.jfif' },
        { en: 'ski downhill', fi: 'lasketella', img: 'verbs2/ski_downhill.jfif' },
        { en: 'smell', fi: 'haistaa', img: 'verbs2/smell.jfif' },
        { en: 'swim', fi: 'uida', img: 'verbs2/swim.jfif' },
        { en: 'taste', fi: 'maistaa', img: 'verbs2/taste.jfif' },
        { en: 'throw', fi: 'heittää', img: 'verbs2/throw.jfif' },
        { en: 'vacuum', fi: 'imuroita', img: 'verbs2/vacuum.jfif' },
        { en: 'wake up', fi: 'herätä', img: 'verbs2/wake_up.jfif' }
      ]
    },
    
    {
      name: 'Adjektiivit — Adjectives',
      wordsAndImages: [
        { en: 'bad', fi: 'huono', img: 'adjectives/bad.png' },
        { en: 'big', fi: 'iso', img: 'adjectives/big.png' },
        { en: 'black', fi: 'musta', img: 'adjectives/black.png' },
        { en: 'blue', fi: 'sininen', img: 'adjectives/blue.png' },
        { en: 'brown', fi: 'ruskea', img: 'adjectives/brown.png' },
        { en: 'clean', fi: 'puhdas', img: 'adjectives/clean.png' },
        { en: 'cold', fi: 'kylmä', img: 'adjectives/cold.png' },
        { en: 'difficult', fi: 'vaikea', img: 'adjectives/difficult.png' },
        { en: 'dirty', fi: 'likainen', img: 'adjectives/dirty.png' },
        { en: 'easy', fi: 'helppo', img: 'adjectives/easy.png' },
        { en: 'fast', fi: 'nopea', img: 'adjectives/fast.png' },
        { en: 'good', fi: 'hyvä', img: 'adjectives/good.png' },
        { en: 'green', fi: 'vihreä', img: 'adjectives/green.png' },
        { en: 'high', fi: 'korkea', img: 'adjectives/high.png' },
        { en: 'hot', fi: 'kuuma', img: 'adjectives/hot.png' },
        { en: 'long', fi: 'pitkä', img: 'adjectives/long.png' },
        { en: 'low', fi: 'matala', img: 'adjectives/low.png' },
        { en: 'new', fi: 'uusi', img: 'adjectives/new.png' },
        { en: 'old', fi: 'vanha', img: 'adjectives/old.png' },
        { en: 'red', fi: 'punainen', img: 'adjectives/red.png' },
        { en: 'short', fi: 'lyhyt', img: 'adjectives/short.png' },
        { en: 'slow', fi: 'hidas', img: 'adjectives/slow.png' },
        { en: 'small', fi: 'pieni', img: 'adjectives/small.png' },
        { en: 'warm', fi: 'lämmin', img: 'adjectives/warm.png' },
        { en: 'white', fi: 'valkoinen', img: 'adjectives/white.png' },
        { en: 'yellow', fi: 'keltainen', img: 'adjectives/yellow.png' }
      ]
    },
    
    {
      name: 'Vaatteet — Clothing',
      wordsAndImages: [
        { en: 'backpack', fi: 'reppu', img: 'clothing/backpack.png' },
        { en: 'belt', fi: 'vyö', img: 'clothing/belt.png' },
        { en: 'boots', fi: 'saappaat', img: 'clothing/boots.png' },
        { en: 'cap', fi: 'lippis', img: 'clothing/cap.png' },
        { en: 'dress', fi: 'mekko', img: 'clothing/dress.png' },
        { en: 'earrings', fi: 'korvakorut', img: 'clothing/earrings.png' },
        { en: 'gloves', fi: 'käsineet', img: 'clothing/gloves.png' },
        { en: 'handbag', fi: 'käsilaukku', img: 'clothing/handbag.png' },
        { en: 'hat', fi: 'hattu', img: 'clothing/hat.png' },
        { en: 'jacket', fi: 'takki', img: 'clothing/jacket.png' },
        { en: 'jeans', fi: 'farkut', img: 'clothing/jeans.png' },
        { en: 'necklace', fi: 'kaulakoru', img: 'clothing/necklace.png' },
        { en: 'ring', fi: 'sormus', img: 'clothing/ring.png' },
        { en: 'sandals', fi: 'sandaalit', img: 'clothing/sandals.png' },
        { en: 'scarf', fi: 'huivi', img: 'clothing/scarf.png' },
        { en: 'shirt', fi: 'paita', img: 'clothing/shirt.png' },
        { en: 'shoes', fi: 'kengät', img: 'clothing/shoes.png' },
        { en: 'shorts', fi: 'shortsit', img: 'clothing/shorts.png' },
        { en: 'skirt', fi: 'hame', img: 'clothing/skirt.png' },
        { en: 'socks', fi: 'sukat', img: 'clothing/socks.png' },
        { en: 'sunglasses', fi: 'aurinkolasit', img: 'clothing/sunglasses.png' },
        { en: 'sweater', fi: 'villapaita', img: 'clothing/sweater.png' },
        { en: 't-shirt', fi: 'T-paita', img: 'clothing/t-shirt.png' },
        { en: 'tie', fi: 'solmio', img: 'clothing/tie.png' },
        { en: 'trousers', fi: 'housut', img: 'clothing/trousers.png' },
        { en: 'umbrella', fi: 'sateenvarjo', img: 'clothing/umbrella.png' },
        { en: 'wallet', fi: 'lompakko', img: 'clothing/wallet.png' },
        { en: 'watch', fi: 'rannekello', img: 'clothing/watch.png' }
      ]
    },
    
    {
      name: 'Terveys — Health',
      wordsAndImages: [
        { en: 'ambulance', fi: 'ambulanssi', img: 'health/ambulance.png' },
        { en: 'bacteria', fi: 'bakteeri', img: 'health/bacteria.png' },
        { en: 'bandage', fi: 'side', img: 'health/bandage.png' },
        { en: 'cough', fi: 'yskä', img: 'health/cough.png' },
        { en: 'dentist', fi: 'hammaslääkäri', img: 'health/dentist.png' },
        { en: 'doctor', fi: 'lääkäri', img: 'health/doctor.png' },
        { en: 'fever', fi: 'kuume', img: 'health/fever.png' },
        { en: 'headache', fi: 'päänsärky', img: 'health/headache.png' },
        { en: 'health center', fi: 'terveysasema', img: 'health/health_center.png' },
        { en: 'hospital', fi: 'sairaala', img: 'health/hospital.png' },
        { en: 'illness', fi: 'sairaus', img: 'health/illness.png' },
        { en: 'medicine', fi: 'lääke', img: 'health/medicine.png' },
        { en: 'nurse', fi: 'sairaanhoitaja', img: 'health/nurse.png' },
        { en: 'pharmacy', fi: 'apteekki', img: 'health/pharmacy.png' },
        { en: 'pill', fi: 'tabletti', img: 'health/pill.png' },
        { en: 'runny nose', fi: 'nuha', img: 'health/runny_nose.png' },
        { en: 'thermometer', fi: 'kuumemittari', img: 'health/thermometer.png' },
        { en: 'vaccine', fi: 'rokote', img: 'health/vaccine.png' },
        { en: 'virus', fi: 'virus', img: 'health/virus.png' }
      ]
    },
    
    {
      name: 'Paikat — Places',
      wordsAndImages: [
        { en: 'airport', fi: 'lentokenttä', img: 'places/airport.png' },
        { en: 'bakery', fi: 'leipomo', img: 'places/bakery.png' },
        { en: 'bank', fi: 'pankki', img: 'places/bank.png' },
        { en: 'bridge', fi: 'silta', img: 'places/bridge.png' },
        { en: 'bus stop', fi: 'bussipysäkki', img: 'places/bus_stop.png' },
        { en: 'café', fi: 'kahvila', img: 'places/café.png' },
        { en: 'fire station', fi: 'palolaitos', img: 'places/fire_station.png' },
        { en: 'gas station', fi: 'huoltoasema', img: 'places/gas_station.png' },
        { en: 'grocery store', fi: 'ruokakauppa', img: 'places/grocery_store.png' },
        { en: 'hospital', fi: 'sairaala', img: 'places/hospital.png' },
        { en: 'hotel', fi: 'hotelli', img: 'places/hotel.png' },
        { en: 'left', fi: 'vasen', img: 'places/left.png' },
        { en: 'library', fi: 'kirjasto', img: 'places/library.png' },
        { en: 'park', fi: 'puisto', img: 'places/park.png' },
        { en: 'pharmacy', fi: 'apteekki', img: 'places/pharmacy.png' },
        { en: 'playground', fi: 'leikkipaikka', img: 'places/playground.png' },
        { en: 'police station', fi: 'poliisiasema', img: 'places/police_station.png' },
        { en: 'post office', fi: 'postitoimisto', img: 'places/post_office.png' },
        { en: 'restaurant', fi: 'ravintola', img: 'places/restaurant.png' },
        { en: 'right', fi: 'oikea', img: 'places/right.png' },
        { en: 'road', fi: 'tie', img: 'places/road.png' },
        { en: 'school', fi: 'koulu', img: 'places/school.png' },
        { en: 'straight', fi: 'suoraan', img: 'places/straight.png' },
        { en: 'street', fi: 'katu', img: 'places/street.png' },
        { en: 'supermarket', fi: 'supermarket', img: 'places/supermarket.png' },
        { en: 'traffic light', fi: 'liikennevalot', img: 'places/traffic_light.png' },
        { en: 'train station', fi: 'rautatieasema', img: 'places/train_station.png' },
        { en: 'tunnel', fi: 'tunneli', img: 'places/tunnel.png' }
      ]
    },
    
    {
      name: 'Ostokset ja raha — Shopping and Money',
      wordsAndImages: [
        { en: 'ATM', fi: 'pankkiautomaatti', img: 'shopping_and_money/ATM.png' },
        { en: 'bank', fi: 'pankki', img: 'shopping_and_money/bank.png' },
        { en: 'banknote', fi: 'seteli', img: 'shopping_and_money/banknote.png' },
        { en: 'barcode', fi: 'viivakoodi', img: 'shopping_and_money/barcode.png' },
        { en: 'cash', fi: 'käteinen', img: 'shopping_and_money/cash.png' },
        { en: 'cashier', fi: 'kassa', img: 'shopping_and_money/cashier.png' },
        { en: 'checkout', fi: 'kassapiste', img: 'shopping_and_money/checkout.png' },
        { en: 'coin', fi: 'kolikko', img: 'shopping_and_money/coin.png' },
        { en: 'credit card', fi: 'luottokortti', img: 'shopping_and_money/credit_card.png' },
        { en: 'customer', fi: 'asiakas', img: 'shopping_and_money/customer.png' },
        { en: 'euro banknote', fi: 'euroseteli', img: 'shopping_and_money/euro_banknote.png' },
        { en: 'grocery store', fi: 'ruokakauppa', img: 'shopping_and_money/grocery_store.png' },
        { en: 'hardware store', fi: 'rautakauppa', img: 'shopping_and_money/hardware_store.png' },
        { en: 'kiosk', fi: 'kioski', img: 'shopping_and_money/kiosk.png' },
        { en: 'mall', fi: 'kauppakeskus', img: 'shopping_and_money/mall.png' },
        { en: 'money', fi: 'raha', img: 'shopping_and_money/money.png' },
        { en: 'plastic bag', fi: 'muovipussi', img: 'shopping_and_money/plastic_bag.png' },
        { en: 'price tag', fi: 'hintalappu', img: 'shopping_and_money/price_tag.png' },
        { en: 'purse', fi: 'kukkaro', img: 'shopping_and_money/purse.png' },
        { en: 'receipt', fi: 'kuitti', img: 'shopping_and_money/receipt.png' },
        { en: 'sale', fi: 'ale', img: 'shopping_and_money/sale.png' },
        { en: 'shelf', fi: 'hylly', img: 'shopping_and_money/shelf.png' },
        { en: 'shopping basket', fi: 'ostoskori', img: 'shopping_and_money/shopping_basket.png' },
        { en: 'shopping cart', fi: 'ostoskärry', img: 'shopping_and_money/shopping_cart.png' },
        { en: 'shopping mall', fi: 'kauppakeskus', img: 'shopping_and_money/shopping_mall.png' },
        { en: 'supermarket', fi: 'supermarket', img: 'shopping_and_money/supermarket.png' },
        { en: 'wallet', fi: 'lompakko', img: 'shopping_and_money/wallet.png' }
      ]
    },
    {
      name: 'Teknologia — Technology',
      wordsAndImages: [
        { en: 'battery', fi: 'akku', img: 'technology/battery.png' },
        { en: 'camera', fi: 'kamera', img: 'technology/camera.png' },
        { en: 'charger', fi: 'laturi', img: 'technology/charger.png' },
        { en: 'computer', fi: 'tietokone', img: 'technology/computer.png' },
        { en: 'email', fi: 'sähköposti', img: 'technology/email.png' },
        { en: 'factory', fi: 'tehdas', img: 'technology/factory.png' },
        { en: 'headphones', fi: 'kuulokkeet', img: 'technology/headphones.png' },
        { en: 'keyboard', fi: 'näppäimistö', img: 'technology/keyboard.png' },
        { en: 'laptop', fi: 'läppäri', img: 'technology/laptop.png' },
        { en: 'loudspeaker', fi: 'kaiutin', img: 'technology/loudspeaker.png' },
        { en: 'microphone', fi: 'mikrofoni', img: 'technology/microphone.png' },
        { en: 'monitor', fi: 'näyttö', img: 'technology/monitor.png' },
        { en: 'mouse', fi: 'hiiri', img: 'technology/mouse.png' },
        { en: 'printer', fi: 'tulostin', img: 'technology/printer.png' },
        { en: 'remote control', fi: 'kaukosäädin', img: 'technology/remote_control.png' },
        { en: 'robot', fi: 'robotti', img: 'technology/robot.png' },
        { en: 'smartphone', fi: 'älypuhelin', img: 'technology/smartphone.png' },
        { en: 'social media', fi: 'sosiaalinen media', img: 'technology/social_media.png' },
        { en: 'USB stick', fi: 'muistitikku', img: 'technology/USB_stick.png' },
        { en: 'video call', fi: 'videopuhelu', img: 'technology/video_call.png' },
        { en: 'website', fi: 'verkkosivusto', img: 'technology/website.png' }
      ]
    },
    
    {
      name: 'Sää ja luonto — Weather and Nature',
      wordsAndImages: [
        { en: 'cloud', fi: 'pilvi', img: 'weather_and_nature/cloud.png' },
        { en: 'cold', fi: 'kylmä', img: 'weather_and_nature/cold.png' },
        { en: 'flower', fi: 'kukka', img: 'weather_and_nature/flower.png' },
        { en: 'forest', fi: 'metsä', img: 'weather_and_nature/forest.png' },
        { en: 'grass', fi: 'ruoho', img: 'weather_and_nature/grass.png' },
        { en: 'hot', fi: 'kuuma', img: 'weather_and_nature/hot.png' },
        { en: 'lake', fi: 'järvi', img: 'weather_and_nature/lake.png' },
        { en: 'leaf', fi: 'lehti', img: 'weather_and_nature/leaf.png' },
        { en: 'mountain', fi: 'vuori', img: 'weather_and_nature/mountain.png' },
        { en: 'mushroom', fi: 'sieni', img: 'weather_and_nature/mushroom.png' },
        { en: 'rain', fi: 'sade', img: 'weather_and_nature/rain.png' },
        { en: 'rainbow', fi: 'sateenkaari', img: 'weather_and_nature/rainbow.png' },
        { en: 'river', fi: 'joki', img: 'weather_and_nature/river.png' },
        { en: 'rock', fi: 'kivi', img: 'weather_and_nature/rock.png' },
        { en: 'sand', fi: 'hiekka', img: 'weather_and_nature/sand.png' },
        { en: 'sea', fi: 'meri', img: 'weather_and_nature/sea.png' },
        { en: 'sky', fi: 'taivas', img: 'weather_and_nature/sky.png' },
        { en: 'snow', fi: 'lumi', img: 'weather_and_nature/snow.png' },
        { en: 'storm', fi: 'myrsky', img: 'weather_and_nature/storm.png' },
        { en: 'sun', fi: 'aurinko', img: 'weather_and_nature/sun.png' },
        { en: 'thermometer', fi: 'lämpömittari', img: 'weather_and_nature/thermometer.png' },
        { en: 'thunder', fi: 'ukkonen', img: 'weather_and_nature/thunder.png' },
        { en: 'tree', fi: 'puu', img: 'weather_and_nature/tree.png' },
        { en: 'warm', fi: 'lämmin', img: 'weather_and_nature/warm.png' },
        { en: 'wind', fi: 'tuuli', img: 'weather_and_nature/wind.png' }
      ]
    },
    
    {
      name: 'Harrastukset — Hobbies',
      wordsAndImages: [
        { en: 'badminton', fi: 'sulkapallo', img: 'hobbies/badminton.png' },
        { en: 'basketball', fi: 'koripallo', img: 'hobbies/basketball.png' },
        { en: 'cross-country skiing', fi: 'murtomaahiihto', img: 'hobbies/crosscountry_skiing.png' },
        { en: 'cycling', fi: 'pyöräily', img: 'hobbies/cycling.png' },
        { en: 'downhill skiing', fi: 'laskettelu', img: 'hobbies/downhill_skiing.png' },
        { en: 'drums', fi: 'rummut', img: 'hobbies/drums.png' },
        { en: 'football', fi: 'jalkapallo', img: 'hobbies/football.png' },
        { en: 'guitar', fi: 'kitara', img: 'hobbies/guitar.png' },
        { en: 'gym', fi: 'kuntosali', img: 'hobbies/gym.png' },
        { en: 'hiking', fi: 'vaeltaminen', img: 'hobbies/hiking.png' },
        { en: 'ice hockey', fi: 'jääkiekko', img: 'hobbies/ice_hockey.png' },
        { en: 'ice skating', fi: 'luistelu', img: 'hobbies/ice_skating.png' },
        { en: 'painting', fi: 'maalaus', img: 'hobbies/painting.png' },
        { en: 'piano', fi: 'piano', img: 'hobbies/piano.png' },
        { en: 'running', fi: 'juoksu', img: 'hobbies/running.png' },
        { en: 'singing', fi: 'laulaminen', img: 'hobbies/singing.png' },
        { en: 'snowboarding', fi: 'lumilautailu', img: 'hobbies/snowboarding.png' },
        { en: 'swimming', fi: 'uinti', img: 'hobbies/swimming.png' },
        { en: 'tennis', fi: 'tennis', img: 'hobbies/tennis.png' },
        { en: 'video game', fi: 'videopeli', img: 'hobbies/video_game.png' },
        { en: 'yoga', fi: 'jooga', img: 'hobbies/yoga.png' }
      ]
    },
    
    
    {
      name: 'Kehon osat — Body Parts',
      wordsAndImages: [
        { en: 'ankle', fi: 'nilkka', img: 'body_parts/ankle.png' },
        { en: 'arm', fi: 'käsivarsi', img: 'body_parts/arm.png' },
        { en: 'back', fi: 'selkä', img: 'body_parts/back.png' },
        { en: 'chest', fi: 'rinta', img: 'body_parts/chest.png' },
        { en: 'ear', fi: 'korva', img: 'body_parts/ear.png' },
        { en: 'elbow', fi: 'kyynärpää', img: 'body_parts/elbow.png' },
        { en: 'eye', fi: 'silmä', img: 'body_parts/eye.png' },
        { en: 'face', fi: 'kasvot', img: 'body_parts/face.png' },
        { en: 'finger', fi: 'sormi', img: 'body_parts/finger.png' },
        { en: 'foot', fi: 'jalka', img: 'body_parts/foot.png' },
        { en: 'hair', fi: 'hiukset', img: 'body_parts/hair.png' },
        { en: 'hand', fi: 'käsi', img: 'body_parts/hand.png' },
        { en: 'head', fi: 'pää', img: 'body_parts/head.png' },
        { en: 'heel', fi: 'kantapää', img: 'body_parts/heel.png' },
        { en: 'knee', fi: 'polvi', img: 'body_parts/knee.png' },
        { en: 'leg', fi: 'jalka', img: 'body_parts/leg.png' },
        { en: 'mouth', fi: 'suu', img: 'body_parts/mouth.png' },
        { en: 'neck', fi: 'kaula', img: 'body_parts/neck.png' },
        { en: 'nose', fi: 'nenä', img: 'body_parts/nose.png' },
        { en: 'shoulder', fi: 'olkapää', img: 'body_parts/shoulder.png' },
        { en: 'stomach', fi: 'vatsa', img: 'body_parts/stomach.png' },
        { en: 'thumb', fi: 'peukalo', img: 'body_parts/thumb.png' },
        { en: 'toe', fi: 'varvas', img: 'body_parts/toe.png' },
        { en: 'wrist', fi: 'ranne', img: 'body_parts/wrist.png' }
      ]
    },
    
    {
      name: 'Numerot ja aika — Numbers and Time',
      wordsAndImages: [
        { en: 'one', fi: 'yksi', img: 'numbers_and_time/one.png' },
        { en: 'two', fi: 'kaksi', img: 'numbers_and_time/two.png' },
        { en: 'three', fi: 'kolme', img: 'numbers_and_time/three.png' },
        { en: 'four', fi: 'neljä', img: 'numbers_and_time/four.png' },
        { en: 'five', fi: 'viisi', img: 'numbers_and_time/five.png' },
        { en: 'six', fi: 'kuusi', img: 'numbers_and_time/six.png' },
        { en: 'seven', fi: 'seitsemän', img: 'numbers_and_time/seven.png' },
        { en: 'eight', fi: 'kahdeksan', img: 'numbers_and_time/eight.png' },
        { en: 'nine', fi: 'yhdeksän', img: 'numbers_and_time/nine.png' },
        { en: 'ten', fi: 'kymmenen', img: 'numbers_and_time/ten.png' },
        { en: 'clock', fi: 'kello', img: 'numbers_and_time/clock.png' },
        { en: 'hour', fi: 'tunti', img: 'numbers_and_time/hour.png' },
        { en: 'minute', fi: 'minuutti', img: 'numbers_and_time/minute.png' },
        { en: 'second', fi: 'sekunti', img: 'numbers_and_time/second.png' },
        { en: 'calendar', fi: 'kalenteri', img: 'numbers_and_time/calendar.png' },
        { en: 'monday', fi: 'maanantai', img: 'numbers_and_time/monday.png' },
        { en: 'tuesday', fi: 'tiistai', img: 'numbers_and_time/tuesday.png' },
        { en: 'wednesday', fi: 'keskiviikko', img: 'numbers_and_time/wednesday.png' },
        { en: 'thursday', fi: 'torstai', img: 'numbers_and_time/thursday.png' },
        { en: 'friday', fi: 'perjantai', img: 'numbers_and_time/friday.png' },
        { en: 'saturday', fi: 'lauantai', img: 'numbers_and_time/saturday.png' },
        { en: 'sunday', fi: 'sunnuntai', img: 'numbers_and_time/sunday.png' },
        { en: 'week', fi: 'viikko', img: 'numbers_and_time/week.png' },
        { en: 'weekend', fi: 'viikonloppu', img: 'numbers_and_time/weekend.png' },
        { en: 'month', fi: 'kuukausi', img: 'numbers_and_time/month.png' },
        { en: 'morning', fi: 'aamu', img: 'numbers_and_time/morning.png' },
        { en: 'evening', fi: 'ilta', img: 'numbers_and_time/evening.png' },
        { en: 'night', fi: 'yö', img: 'numbers_and_time/night.png' },
        { en: 'spring', fi: 'kevät', img: 'numbers_and_time/spring.png' },
        { en: 'summer', fi: 'kesä', img: 'numbers_and_time/summer.png' },
        { en: 'autumn', fi: 'syksy', img: 'numbers_and_time/autumn.png' },
        { en: 'winter', fi: 'talvi', img: 'numbers_and_time/winter.png' }
      ]
    }
    
    
    
    
    
    
    
    
    ]